
POST http://localhost:3200/signup
Content-Type: application/json

{
      "username": "testuser",
      "email": "test@user.com",
      "password": "testuser",
      "firstName": "Test",
      "lastName": "User",
      "country": "BG",
      "address": "Sofia",
      "phoneNumber": "0892719063"
}

POST http://localhost:3200/login
Content-Type: application/json

{
      "username": "testuser",
      "password": "testuser2"
}
