
POST http://localhost:3200/signup
Content-Type: application/json

{
      "username": "testuser1",
      "email": "test1@user.com",
      "password": "testuser",
      "firstName": "Test",
      "lastName": "User",
      "country": "BG",
      "address": "Sofia",
      "phoneNumber": "0892719063"
}

POST http://localhost:3200/login
Content-Type: application/json

{
      "username": "testuser1",
      "password": "testuser"
}

GET http://localhost:3200/me

GET http://localhost:3200/wallet


DELETE http://localhost:3200/logout

POST http://localhost:3200/wallet/card
Content-Type: application/json

{
      "cardNumber": "1111222233334447",
      "cardHolderName": "Test User",
      "expirationDate": "10/23",
      "CVV": "123"
}