GET http://localhost:3200/me
Content-Type: application/json


POST http://localhost:3200/signup
Content-Type: application/json

{
      "username": "test",
      "email": "test@user.com",
      "password": "usertest",
      "firstName": "Test",
      "lastName": "User",
      "country": "BG",
      "address": "Sofia",
      "phoneNumber": "+3591948"
}
